[server]
name = 'cosigner'
port = 8080

[eosio]
# The default API server for requests
api_default = 'http://jungle3.greymass.com'

# A modified nodeos instance to sample transaction billing times
#   https://github.com/greymass/eos/tree/skip_all_checks
api_sampler = 'http://jungle3.greymass.com'

# The ID of the chain in use
chain_id = '2a02a0053e5a8cf73a56ba0fda11e4d92e0238a4a2aa74fccf46d5a910746840'
system_token = '4,EOS'

# The maximum number of milliseconds for any transaction
max_cpu_usage_ms = 5

[account]
# Name and Permission of the account to sign with (should be a key permissions linked only to greymassnoop:noop)
#   example: 'cosign' key permission on 'cosigncosign' account 
#            https://jungle3.bloks.io/account/cosigncosign#keys
name = 'cosigncosign'
permission = 'cosign'

# Private Key for the above permission
key = '5KKpyicaUXaRvTKN54JYK1GEeu6FN3s3YyRLPdrHNp2prV7m96x'

[[log]]
level = 'debug'
out = 'stdout'
